apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2020-12-08T15:36:15Z"
  generation: 1
  labels:
    app: covidtracerbackend
  name: covidtracerbackend
  namespace: default
  resourceVersion: "539750"
  selfLink: /apis/apps/v1/namespaces/default/deployments/covidtracerbackend
  uid: 00ec287f-b86c-4f93-8eb9-0b25195ecc2c
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: covidtracerbackend
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: covidtracerbackend
    spec:
      containers:
      - image: us.gcr.io/poc-covidtracer-19938u1-195611/covidtracerservice:latest
        imagePullPolicy: Always
        name: covidtracerservice-1
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  conditions:
  - lastTransitionTime: "2020-12-08T15:36:15Z"
    lastUpdateTime: "2020-12-08T15:36:15Z"
    message: Deployment does not have minimum availability.
    reason: MinimumReplicasUnavailable
    status: "False"
    type: Available
  - lastTransitionTime: "2020-12-08T15:36:15Z"
    lastUpdateTime: "2020-12-08T15:39:46Z"
    message: ReplicaSet "covidtracerbackend-66b795979b" is progressing.
    reason: ReplicaSetUpdated
    status: "True"
    type: Progressing
  observedGeneration: 1
  replicas: 3
  unavailableReplicas: 3
  updatedReplicas: 3
